BULK INSERT Hotel
FROM 'data_Hotel.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Airport
FROM 'data_Airport.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT AirportNearHotel
FROM 'data_AirportNearHotel.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT HotelOffer
FROM 'data_HotelOffer.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Flight
FROM 'data_Flight.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Ariline
FROM 'data_Ariline.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT TravelAgency
FROM 'data_TravelAgency.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT TravelBetween
FROM 'data_TravelBetween.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT ParadiseOffer
FROM 'data_ParadiseOffer.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Employee
FROM 'data_Employee.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Client
FROM 'data_Client.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT ClientOffer
FROM 'data_ClientOffer.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Payment
FROM 'data_Payment.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Opinion
FROM 'data_Opinion.csv0'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Hotel
FROM 'data_Hotel.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Airport
FROM 'data_Airport.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT AirportNearHotel
FROM 'data_AirportNearHotel.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT HotelOffer
FROM 'data_HotelOffer.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Flight
FROM 'data_Flight.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Ariline
FROM 'data_Ariline.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT TravelAgency
FROM 'data_TravelAgency.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT TravelBetween
FROM 'data_TravelBetween.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT ParadiseOffer
FROM 'data_ParadiseOffer.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Employee
FROM 'data_Employee.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Client
FROM 'data_Client.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT ClientOffer
FROM 'data_ClientOffer.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Payment
FROM 'data_Payment.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

BULK INSERT Opinion
FROM 'data_Opinion.csv1'
WITH (FIRSTROW = 2,
FIELDTERMINATOR = '|',
ROWTERMINATOR='0x0a');

